import os
import sys

def resource_path(relative_path):
    """ Get absolute path to resource, works for dev and for PyInstaller """
    try:
        # PyInstaller creates a temp folder and stores path in _MEIPASS
        base_path = sys._MEIPASS
    except AttributeError:
        base_path = os.path.abspath(".")

    return os.path.join(base_path, relative_path)

# Form implementation generated from reading ui file 'TempGUI.ui'
#
# Created by: PyQt6 UI code generator 6.7.1
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(929, 666)
        MainWindow.setAnimated(False)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CommPortSelect = QtWidgets.QComboBox(parent=self.centralwidget)
        self.CommPortSelect.setGeometry(QtCore.QRect(20, 480, 241, 31))
        self.CommPortSelect.setObjectName("CommPortSelect")
        self.Connect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.Connect.setGeometry(QtCore.QRect(140, 520, 114, 34))
        self.Connect.setStyleSheet("QPushButton:enabled {\n"
"    background-color : green;\n"
"    color : white;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}")
        self.Connect.setObjectName("Connect")
        self.RefreshComm = QtWidgets.QPushButton(parent=self.centralwidget)
        self.RefreshComm.setGeometry(QtCore.QRect(20, 520, 114, 34))
        self.RefreshComm.setStyleSheet("QPushButton:enabled {\n"
"    background-color : rgb(255, 167, 14);\n"
"    color : black;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}")
        self.RefreshComm.setObjectName("RefreshComm")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 450, 231, 26))
        self.label.setObjectName("label")
        self.TempChan0 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.TempChan0.setGeometry(QtCore.QRect(30, 50, 301, 91))
        self.TempChan0.setDigitCount(6)
        self.TempChan0.setObjectName("TempChan0")
        self.TempChan1 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.TempChan1.setGeometry(QtCore.QRect(600, 50, 291, 91))
        self.TempChan1.setDigitCount(6)
        self.TempChan1.setObjectName("TempChan1")
        self.TempChan2 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.TempChan2.setGeometry(QtCore.QRect(30, 230, 301, 91))
        self.TempChan2.setDigitCount(6)
        self.TempChan2.setObjectName("TempChan2")
        self.TempChan3 = QtWidgets.QLCDNumber(parent=self.centralwidget)
        self.TempChan3.setGeometry(QtCore.QRect(600, 230, 291, 91))
        self.TempChan3.setDigitCount(6)
        self.TempChan3.setObjectName("TempChan3")
        self.progressBar = QtWidgets.QProgressBar(parent=self.centralwidget)
        self.progressBar.setGeometry(QtCore.QRect(280, 590, 301, 27))
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.label_3 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 560, 191, 26))
        self.label_3.setObjectName("label_3")
        self.ExportSheet = QtWidgets.QPushButton(parent=self.centralwidget)
        self.ExportSheet.setGeometry(QtCore.QRect(770, 550, 141, 61))
        self.ExportSheet.setStyleSheet("QPushButton:enabled {\n"
"    background-color : red;\n"
"    color : black;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}")
        self.ExportSheet.setObjectName("ExportSheet")
        self.LogPathSelect = QtWidgets.QPushButton(parent=self.centralwidget)
        self.LogPathSelect.setGeometry(QtCore.QRect(420, 390, 161, 34))
        self.LogPathSelect.setObjectName("LogPathSelect")
        self.label_5 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(280, 390, 91, 26))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(30, 20, 41, 26))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(600, 20, 41, 26))
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(600, 200, 41, 26))
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(30, 200, 41, 26))
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(30, 140, 71, 26))
        self.label_10.setObjectName("label_10")
        self.Chan0Name = QtWidgets.QLabel(parent=self.centralwidget)
        self.Chan0Name.setGeometry(QtCore.QRect(100, 140, 201, 26))
        self.Chan0Name.setText("")
        self.Chan0Name.setObjectName("Chan0Name")
        self.arrayStatus0 = QtWidgets.QLabel(parent=self.centralwidget)
        self.arrayStatus0.setGeometry(QtCore.QRect(70, 20, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.arrayStatus0.setFont(font)
        self.arrayStatus0.setText("")
        self.arrayStatus0.setObjectName("arrayStatus0")
        self.array1Status = QtWidgets.QLabel(parent=self.centralwidget)
        self.array1Status.setGeometry(QtCore.QRect(640, 20, 201, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.array1Status.setFont(font)
        self.array1Status.setText("")
        self.array1Status.setObjectName("array1Status")
        self.array3Status = QtWidgets.QLabel(parent=self.centralwidget)
        self.array3Status.setGeometry(QtCore.QRect(640, 200, 191, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.array3Status.setFont(font)
        self.array3Status.setText("")
        self.array3Status.setObjectName("array3Status")
        self.array2Status = QtWidgets.QLabel(parent=self.centralwidget)
        self.array2Status.setGeometry(QtCore.QRect(70, 200, 191, 26))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.array2Status.setFont(font)
        self.array2Status.setText("")
        self.array2Status.setObjectName("array2Status")
        self.Chan1Name = QtWidgets.QLabel(parent=self.centralwidget)
        self.Chan1Name.setGeometry(QtCore.QRect(670, 140, 191, 26))
        self.Chan1Name.setText("")
        self.Chan1Name.setObjectName("Chan1Name")
        self.label_11 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(600, 140, 71, 26))
        self.label_11.setObjectName("label_11")
        self.Chan2Name = QtWidgets.QLabel(parent=self.centralwidget)
        self.Chan2Name.setGeometry(QtCore.QRect(90, 320, 201, 26))
        self.Chan2Name.setText("")
        self.Chan2Name.setObjectName("Chan2Name")
        self.label_12 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(30, 320, 71, 26))
        self.label_12.setObjectName("label_12")
        self.Chan3Name = QtWidgets.QLabel(parent=self.centralwidget)
        self.Chan3Name.setGeometry(QtCore.QRect(670, 320, 191, 26))
        self.Chan3Name.setText("")
        self.Chan3Name.setObjectName("Chan3Name")
        self.label_13 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(600, 320, 71, 26))
        self.label_13.setObjectName("label_13")
        self.line_2 = QtWidgets.QFrame(parent=self.centralwidget)
        self.line_2.setGeometry(QtCore.QRect(-30, 370, 981, 20))
        self.line_2.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_2.setObjectName("line_2")
        self.ExportPeriod = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.ExportPeriod.setGeometry(QtCore.QRect(600, 470, 181, 30))
        self.ExportPeriod.setObjectName("ExportPeriod")
        self.TimeUnitSelect_2 = QtWidgets.QComboBox(parent=self.centralwidget)
        self.TimeUnitSelect_2.setGeometry(QtCore.QRect(800, 470, 101, 31))
        self.TimeUnitSelect_2.setObjectName("TimeUnitSelect_2")
        self.label_14 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(800, 440, 151, 26))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(600, 440, 101, 26))
        self.label_15.setObjectName("label_15")
        self.logFileNameInput = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.logFileNameInput.setGeometry(QtCore.QRect(280, 500, 311, 30))
        self.logFileNameInput.setText("")
        self.logFileNameInput.setObjectName("logFileNameInput")
        self.label_16 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(280, 470, 81, 26))
        self.label_16.setObjectName("label_16")
        self.StartLog = QtWidgets.QPushButton(parent=self.centralwidget)
        self.StartLog.setGeometry(QtCore.QRect(610, 550, 151, 61))
        self.StartLog.setStyleSheet("QPushButton:enabled {\n"
"    background-color : green;\n"
"    color : white;\n"
"}\n"
"QPushButton:disabled {\n"
"    background-color: lightgray;\n"
"    color: darkgray;\n"
"}")
        self.StartLog.setObjectName("StartLog")
        self.DisableAuto = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.DisableAuto.setGeometry(QtCore.QRect(280, 540, 121, 18))
        self.DisableAuto.setObjectName("DisableAuto")
        self.GraphChan0 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphChan0.setGeometry(QtCore.QRect(300, 140, 31, 31))
        self.GraphChan0.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(resource_path("chart.png")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.GraphChan0.setIcon(icon)
        self.GraphChan0.setObjectName("GraphChan0")
        self.GraphChan2 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphChan2.setGeometry(QtCore.QRect(300, 320, 31, 31))
        self.GraphChan2.setText("")
        self.GraphChan2.setIcon(icon)
        self.GraphChan2.setObjectName("GraphChan2")
        self.GraphChan1 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphChan1.setGeometry(QtCore.QRect(860, 140, 31, 31))
        self.GraphChan1.setText("")
        self.GraphChan1.setIcon(icon)
        self.GraphChan1.setObjectName("GraphChan1")
        self.GraphChan3 = QtWidgets.QPushButton(parent=self.centralwidget)
        self.GraphChan3.setGeometry(QtCore.QRect(860, 320, 31, 31))
        self.GraphChan3.setText("")
        self.GraphChan3.setIcon(icon)
        self.GraphChan3.setObjectName("GraphChan3")
        self.FilePath = QtWidgets.QLabel(parent=self.centralwidget)
        self.FilePath.setGeometry(QtCore.QRect(280, 430, 301, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.FilePath.setFont(font)
        self.FilePath.setText("")
        self.FilePath.setObjectName("FilePath")
        self.line = QtWidgets.QFrame(parent=self.centralwidget)
        self.line.setGeometry(QtCore.QRect(260, 380, 20, 281))
        self.line.setFrameShape(QtWidgets.QFrame.Shape.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Connect.setText(_translate("MainWindow", "Connect"))
        self.RefreshComm.setText(_translate("MainWindow", "Refresh"))
        self.label.setText(_translate("MainWindow", "Connect to COM Port:"))
        self.label_3.setText(_translate("MainWindow", "Till next log export:"))
        self.ExportSheet.setText(_translate("MainWindow", "Stop Save Log"))
        self.LogPathSelect.setText(_translate("MainWindow", "Select File Path"))
        self.label_5.setText(_translate("MainWindow", "Log file Path:"))
        self.label_6.setText(_translate("MainWindow", "Chan 1:"))
        self.label_7.setText(_translate("MainWindow", "Chan 2:"))
        self.label_8.setText(_translate("MainWindow", "Chan 4:"))
        self.label_9.setText(_translate("MainWindow", "Chan 3:"))
        self.label_10.setText(_translate("MainWindow", "ArrayName:"))
        self.label_11.setText(_translate("MainWindow", "ArrayName:"))
        self.label_12.setText(_translate("MainWindow", "ArrayName:"))
        self.label_13.setText(_translate("MainWindow", "ArrayName:"))
        self.label_14.setText(_translate("MainWindow", "Unit:"))
        self.label_15.setText(_translate("MainWindow", "Log Export Period:"))
        self.label_16.setText(_translate("MainWindow", "Log File Name"))
        self.StartLog.setText(_translate("MainWindow", "Start Logging"))
        self.DisableAuto.setText(_translate("MainWindow", "Disable Auto Log"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
